#!/bin/bash

SOURCE="$1"

if [ -z "$SOURCE" ]; then
    echo "Usage: $0 <image>"
    exit 1
fi

if [ ! -f "$SOURCE" ]; then
    echo "File not found:"
    echo "$SOURCE"
    exit 1
fi

install -Dm644 \
    "$SOURCE" \
    /usr/share/backgrounds/custom/current-wallpaper.png
